<a class="anchor" id='import'>
<font color = '#006400'>
    
# **1. Data Integration** </font>
</a>

<a class="anchor" id='lib'></a>
<font color = '#008000'>

## **1.1. Import the needed libraries** </font>

In [38]:
import pandas as pd

<a class="anchor" id='lib'></a>
<font color = '#008000'>

## **1.2. Integrate the datasets into the notebook** </font>

In [39]:
#Import u.data dataset
#ratings_path = "../data/ml-100k/u.data"

import requests
from io import StringIO

url_data = "https://files.grouplens.org/datasets/movielens/ml-100k/u.data"
columns = ['userId', 'movieId', 'rating', 'timestamp']

# Download the data ignoring SSL verification
response = requests.get(url_data, verify=False)  
data = StringIO(response.text)

ratings = pd.read_csv(data, sep='\t', names=columns)
print(ratings.head())

c:\Users\carla\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'files.grouplens.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

   userId  movieId  rating  timestamp
0     196      242       3  881250949
1     186      302       3  891717742
2      22      377       1  878887116
3     244       51       2  880606923
4     166      346       1  886397596

In [40]:
#Import u.item dataset
#items_path = "../data/ml-100k/u.item"

url_item = "https://files.grouplens.org/datasets/movielens/ml-100k/u.item"

item_columns = [
    'movieId', 'title', 'release_date', 'video_release_date', 'IMDb_URL',
    'unknown', 'Action', 'Adventure', 'Animation', "Children's", 'Comedy',
    'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror',
    'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western'
]

# Download file while ignoring SSL verification
response = requests.get(url_item, verify=False)
data = StringIO(response.text)

# Read the file using correct separator and encoding
movies = pd.read_csv(data, sep='|', names=item_columns, encoding='latin-1')

print(movies.head())

c:\Users\carla\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'files.grouplens.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

   movieId              title release_date  video_release_date  \
0        1   Toy Story (1995)  01-Jan-1995                 NaN
1        2   GoldenEye (1995)  01-Jan-1995                 NaN
2        3  Four Rooms (1995)  01-Jan-1995                 NaN
3        4  Get Shorty (1995)  01-Jan-1995                 NaN
4        5     Copycat (1995)  01-Jan-1995                 NaN

                                            IMDb_URL  unknown  Action  \
0  http://us.imdb.com/M/title-exact?Toy%20Story%2...        0       0
1  http://us.imdb.com/M/title-exact?GoldenEye%20(...        0       1
2  http://us.imdb.com/M/title-exact?Four%20Rooms%...        0       0
3  http://us.imdb.com/M/title-exact?Get%20Shorty%...        0       1
4  http://us.imdb.com/M/title-exact?Copycat%20(1995)        0       0

   Adventure  Animation  Children's  ...  Fantasy  Film-Noir  Horror  Musical  \
0          0          1           1  ...        0          0       0        0
1          1          0           0  ...        0          0       0        0
2          0          0           0  ...        0          0       0        0
3          0          0           0  ...        0          0       0        0
4          0          0           0  ...        0          0       0        0

   Mystery  Romance  Sci-Fi  Thriller  War  Western
0        0        0       0         0    0        0
1        0        0       0         1    0        0
2        0        0       0         1    0        0
3        0        0       0         0    0        0
4        0        0       0         1    0        0

[5 rows x 24 columns]

In [41]:
#Import u.user dataset
#users_path = "../data/ml-100k/u.user"

url_user = "https://files.grouplens.org/datasets/movielens/ml-100k/u.user"

user_columns = ['userId', 'age', 'gender', 'occupation', 'zip_code']

# Download file while ignoring SSL verification
response = requests.get(url_user, verify=False)
data = StringIO(response.text)

# Read dataset
users = pd.read_csv(data, sep='|', names=user_columns)

print(users.head())

c:\Users\carla\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'files.grouplens.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

   userId  age gender  occupation zip_code
0       1   24      M  technician    85711
1       2   53      F       other    94043
2       3   23      M      writer    32067
3       4   24      M  technician    43537
4       5   33      F       other    15213

In [42]:
url_genre = "https://files.grouplens.org/datasets/movielens/ml-100k/u.genre"

genre_columns = ['genre', 'genreId']

# Download file while ignoring SSL verification
response = requests.get(url_genre, verify=False)
data = StringIO(response.text)

genres = pd.read_csv(data, sep='|', names=genre_columns, encoding='latin-1')

print(genres.head())

        genre  genreId
0     unknown        0
1      Action        1
2   Adventure        2
3   Animation        3
4  Children's        4

c:\Users\carla\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'files.grouplens.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [43]:
#Import u.occupation dataset
#occupation_path = "../data/ml-100k/u.occupation"

url_occupation = "https://files.grouplens.org/datasets/movielens/ml-100k/u.occupation"

# Download file while ignoring SSL verification
response = requests.get(url_occupation, verify=False)
data = StringIO(response.text)

occupations = pd.read_csv(data, names=['occupation'], encoding='latin-1')

print(occupations.head())

c:\Users\carla\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'files.grouplens.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

      occupation
0  administrator
1         artist
2         doctor
3       educator
4       engineer

<a class="anchor" id='import'>
<font color = '#006400'>
    
# **2. Data Access, Exploration and Understanding** </font>
</a>

<a class="anchor" id='lib'></a>
<font color = '#008000'>

## **2.1. Ratings** </font>

In [44]:
def cleaning_ratings_data(df):

    # Store original stats
    original_rows = len(df)
    
    # Create copy
    df_clean = df.copy()
    
    print("DATA CLEANING PROCESS")
    print("=" * 50)
    
    # 1. Remove empty columns
    empty_cols = [col for col in df_clean.columns if len(df_clean[col].value_counts()) == 0]
    if empty_cols:
        df_clean.drop(empty_cols, axis=1, inplace=True)
        print(f"✓ Removed empty columns: {empty_cols}")
    else:
        print("✓ No empty columns found")
    
    # 2. Check and remove missing values
    missing_before = df_clean[['userId', 'movieId', 'rating', 'timestamp']].isnull().sum()
    if missing_before.sum() > 0:
        print(f"✓ Found missing values: {dict(missing_before)}")
        df_clean = df_clean.dropna(subset=['userId', 'movieId', 'rating', 'timestamp'])
        missing_after = df_clean[['userId', 'movieId', 'rating', 'timestamp']].isnull().sum()
        print(f"✓ Removed {missing_before.sum() - missing_after.sum()} rows with missing values")
    else:
        print("✓ No missing values found")
    
    # 3. Validate ratings (0.5 to 5.0 with 0.5 increments)
    valid_ratings = [0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]
    invalid_ratings = df_clean[~df_clean['rating'].isin(valid_ratings)]
    if len(invalid_ratings) > 0:
        print(f"✓ Found {len(invalid_ratings)} invalid ratings")
        print(f"✓ Invalid rating values: {sorted(invalid_ratings['rating'].unique())}")
        df_clean = df_clean[df_clean['rating'].isin(valid_ratings)]
        print(f"✓ Removed {len(invalid_ratings)} rows with invalid ratings")
    else:
        print("✓ All ratings are valid (0.5 to 5.0 with 0.5 increments)")
    
    # 4. Remove duplicate user-movie ratings
    duplicates = df_clean.duplicated(subset=['userId', 'movieId']).sum()
    if duplicates > 0:
        print(f"✓ Found {duplicates} duplicate user-movie ratings")
        df_clean = df_clean.drop_duplicates(subset=['userId', 'movieId'])
        print(f"✓ Removed {duplicates} duplicate ratings")
    else:
        print("✓ No duplicate ratings found")
    
    # 5. Validate user and movie IDs
    invalid_users = len(df_clean[df_clean['userId'] <= 0])
    invalid_movies = len(df_clean[df_clean['movieId'] <= 0])
    if invalid_users > 0 or invalid_movies > 0:
        print(f"✓ Found {invalid_users} invalid user IDs and {invalid_movies} invalid movie IDs")
        df_clean = df_clean[(df_clean['userId'] > 0) & (df_clean['movieId'] > 0)]
        print(f"✓ Removed {invalid_users + invalid_movies} rows with invalid IDs")
    else:
        print("✓ All user and movie IDs are valid")
    
    # 6. Process timestamps
    df_clean['rating_date'] = pd.to_datetime(df_clean['timestamp'], unit='s')
    df_clean['rating_year'] = df_clean['rating_date'].dt.year
    df_clean['rating_month'] = df_clean['rating_date'].dt.month
    
    print(f"✓ Added date features: rating_date, rating_year, rating_month")
    
    return df_clean

# Apply cleaning
ratings = cleaning_ratings_data(ratings)

# Display the processed ratings table and summary
print("\n" + "=" * 50)
print("PROCESSED RATINGS TABLE")
print("=" * 50)
print(ratings.head())

print("\n" + "=" * 50)
print("PROCESSING SUMMARY")
print("=" * 50)
print(f"Total ratings: {len(ratings)}")
print(f"Columns: {list(ratings.columns)}")
print(f"Rating range: {ratings['rating'].min()} - {ratings['rating'].max()}")
print(f"Date range: {ratings['rating_year'].min()} - {ratings['rating_year'].max()}")
print(f"Unique users: {ratings['userId'].nunique()}")
print(f"Unique movies: {ratings['movieId'].nunique()}")

DATA CLEANING PROCESS
==================================================
✓ No empty columns found
✓ No missing values found
✓ All ratings are valid (0.5 to 5.0 with 0.5 increments)
✓ No duplicate ratings found
✓ All user and movie IDs are valid
✓ Added date features: rating_date, rating_year, rating_month

==================================================
PROCESSED RATINGS TABLE
==================================================
   userId  movieId  rating  timestamp         rating_date  rating_year  \
0     196      242       3  881250949 1997-12-04 15:55:49         1997
1     186      302       3  891717742 1998-04-04 19:22:22         1998
2      22      377       1  878887116 1997-11-07 07:18:36         1997
3     244       51       2  880606923 1997-11-27 05:02:03         1997
4     166      346       1  886397596 1998-02-02 05:33:16         1998

   rating_month
0            12
1             4
2            11
3            11
4             2

==================================================
PROCESSING SUMMARY
==================================================
Total ratings: 100000
Columns: ['userId', 'movieId', 'rating', 'timestamp', 'rating_date', 'rating_year', 'rating_month']
Rating range: 1 - 5
Date range: 1997 - 1998
Unique users: 943
Unique movies: 1682

In [45]:
# Missing checks for:
ratings.isnull().sum()  # for userId, movieId, rating, timestamp

userId          0
movieId         0
rating          0
timestamp       0
rating_date     0
rating_year     0
rating_month    0
dtype: int64

In [46]:
user_ratings = ratings[ratings['userId'] == 196]
user_ratings

,userId,movieId,rating,timestamp,rating_date,rating_year,rating_month
0,196,242,3,881250949,1997-12-04 15:55:49,1997,12
940,196,393,4,881251863,1997-12-04 16:11:03,1997,12
1133,196,381,4,881251728,1997-12-04 16:08:48,1997,12
1812,196,251,3,881251274,1997-12-04 16:01:14,1997,12
1896,196,655,5,881251793,1997-12-04 16:09:53,1997,12
2374,196,67,5,881252017,1997-12-04 16:13:37,1997,12
6910,196,306,4,881251021,1997-12-04 15:57:01,1997,12
7517,196,238,4,881251820,1997-12-04 16:10:20,1997,12
7842,196,663,5,881251911,1997-12-04 16:11:51,1997,12
10017,196,111,4,881251793,1997-12-04 16:09:53,1997,12
10254,196,580,2,881252056,1997-12-04 16:14:16,1997,12
10981,196,25,4,881251955,1997-12-04 16:12:35,1997,12
13733,196,286,5,881250949,1997-12-04 15:55:49,1997,12
14606,196,94,3,881252172,1997-12-04 16:16:12,1997,12
16834,196,692,5,881252017,1997-12-04 16:13:37,1997,12
17102,196,8,5,881251753,1997-12-04 16:09:13,1997,12
17830,196,428,4,881251702,1997-12-04 16:08:22,1997,12
18853,196,1118,4,881252128,1997-12-04 16:15:28,1997,12
21605,196,70,3,881251842,1997-12-04 16:10:42,1997,12
22271,196,66,3,881251911,1997-12-04 16:11:51,1997,12
22773,196,257,2,881251577,1997-12-04 16:06:17,1997,12
23189,196,108,4,881252110,1997-12-04 16:15:10,1997,12
24030,196,202,3,881251728,1997-12-04 16:08:48,1997,12
25726,196,340,3,881251045,1997-12-04 15:57:25,1997,12
32721,196,287,3,881251884,1997-12-04 16:11:24,1997,12
33536,196,116,3,881251753,1997-12-04 16:09:13,1997,12
35197,196,382,4,881251843,1997-12-04 16:10:43,1997,12
36281,196,285,5,881251753,1997-12-04 16:09:13,1997,12
41539,196,1241,3,881251642,1997-12-04 16:07:22,1997,12
42384,196,1007,4,881251601,1997-12-04 16:06:41,1997,12
50147,196,411,4,881252090,1997-12-04 16:14:50,1997,12
52726,196,153,5,881251820,1997-12-04 16:10:20,1997,12
56628,196,13,2,881251955,1997-12-04 16:12:35,1997,12
59165,196,762,3,881251955,1997-12-04 16:12:35,1997,12
59607,196,173,2,881251820,1997-12-04 16:10:20,1997,12
60199,196,1022,4,881251143,1997-12-04 15:59:03,1997,12
60706,196,845,4,881251954,1997-12-04 16:12:34,1997,12
78787,196,269,3,881250949,1997-12-04 15:55:49,1997,12
87863,196,110,1,881252305,1997-12-04 16:18:25,1997,12

In [47]:
#checking whether user 196 rated the same movie more than once
user_ratings[user_ratings['movieId'].duplicated()]

Empty DataFrame
Columns: [userId, movieId, rating, timestamp, rating_date, rating_year, rating_month]
Index: []

In [48]:
ratings.describe()

,userId,movieId,rating,timestamp,rating_date,rating_year,rating_month
count,100000.00000,100000.000000,100000.000000,1.000000e+05,100000,100000.000000,100000.00000
mean,462.48475,425.530130,3.529860,8.835289e+08,1997-12-31 00:40:51.488619904,1997.471010,6.81569
min,1.00000,1.000000,1.000000,8.747247e+08,1997-09-20 03:05:10,1997.000000,1.00000
25%,254.00000,175.000000,3.000000,8.794487e+08,1997-11-13 19:18:29.500000,1997.000000,2.00000
50%,447.00000,322.000000,4.000000,8.828269e+08,1997-12-22 21:42:24,1997.000000,9.00000
75%,682.00000,631.000000,4.000000,8.882600e+08,1998-02-23 18:53:04,1998.000000,11.00000
max,943.00000,1682.000000,5.000000,8.932866e+08,1998-04-22 23:10:38,1998.000000,12.00000
std,266.61442,330.798356,1.125674,5.343856e+06,NaN,0.499161,4.32036

In [49]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   userId        100000 non-null  int64
 1   movieId       100000 non-null  int64
 2   rating        100000 non-null  int64
 3   timestamp     100000 non-null  int64
 4   rating_date   100000 non-null  datetime64[ns]
 5   rating_year   100000 non-null  int32
 6   rating_month  100000 non-null  int32
dtypes: datetime64[ns](1), int32(2), int64(4)
memory usage: 4.6 MB

<a class="anchor" id='lib'></a>
<font color = '#008000'>

## **2.2. Movies** </font>

In [50]:
movies.head()

,movieId,title,release_date,video_release_date,IMDb_URL,unknown,Action,Adventure,Animation,Children's,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [51]:
def cleaning_movies_data(movies):
    """
    Enhanced cleaning function for movies data with detailed testing summary
    """
    # Store original stats
    original_rows = len(movies)
    
    # Create copy
    movies_clean = movies.copy()
    
    print("MOVIES DATA CLEANING PROCESS")
    print("=" * 50)
    
    # 1. Remove empty and irrelevant columns
    empty_cols = []
    for column in movies_clean.columns:
        if len(movies_clean[column].value_counts()) == 0:
            empty_cols.append(column)
    
    irrelevant_cols = ['IMDb_URL', 'unknown']
    columns_to_remove = empty_cols + [col for col in irrelevant_cols if col in movies_clean.columns]
    
    if columns_to_remove:
        movies_clean.drop(columns_to_remove, axis=1, inplace=True)
        print(f"✓ Removed columns: {columns_to_remove}")
    else:
        print("✓ No columns to remove")
    
    # 2. Remove duplicate movies
    duplicates = movies_clean.duplicated().sum()
    if duplicates > 0:
        print(f"✓ Found {duplicates} duplicate movies")
        movies_clean = movies_clean.drop_duplicates()
        print(f"✓ Removed {duplicates} duplicate movies")
    else:
        print("✓ No duplicate movies found")
    
    # 3. Check for missing values
    missing_before = movies_clean.isnull().sum()
    if missing_before.sum() > 0:
        print(f"✓ Found missing values: {dict(missing_before)}")
        movies_clean = movies_clean.dropna()
        missing_after = movies_clean.isnull().sum()
        print(f"✓ Removed {missing_before.sum() - missing_after.sum()} rows with missing values")
    else:
        print("✓ No missing values found")
    
    # 4. Process release dates
    if 'release_date' in movies_clean.columns:
        movies_clean['release_date'] = pd.to_datetime(movies_clean['release_date'], errors='coerce')
        movies_clean['release_date_year'] = movies_clean['release_date'].dt.year
        movies_clean['release_date_month'] = movies_clean['release_date'].dt.month
        
        # Check for invalid dates
        invalid_dates = movies_clean['release_date'].isna().sum()
        if invalid_dates > 0:
            print(f"✓ Found {invalid_dates} movies with invalid dates")
        else:
            print("✓ All dates are valid")
        
        # Remove invalid release years (before 1900)
        invalid_years = (movies_clean['release_date_year'] < 1900).sum()
        if invalid_years > 0:
            print(f"✓ Found {invalid_years} movies with release year before 1900")
            movies_clean = movies_clean[movies_clean['release_date_year'] >= 1900]
            print(f"✓ Removed {invalid_years} movies with invalid release years")
        else:
            print("✓ All release years are valid (≥ 1900)")
    else:
        print("✓ No release_date column found")
    
    # 5. Clean and validate titles
    if 'title' in movies_clean.columns:
        # Check titles with year pattern
        year_pattern = r'.*\(\d{4}\)$'
        titles_with_year = movies_clean['title'].str.contains(year_pattern, na=False).sum()
        print(f"✓ Found {titles_with_year} titles with year in parentheses")
        
        # Clean titles
        original_titles = movies_clean['title'].copy()
        movies_clean['title'] = movies_clean['title'].str.lower()
        movies_clean['title'] = movies_clean['title'].str.replace(r'\s*\(\d{4}\)$', '', regex=True)
        
        # Check if titles were modified
        titles_modified = (original_titles != movies_clean['title']).sum()
        print(f"✓ Modified {titles_modified} titles (lowercase + removed years)")
    else:
        print("✓ No title column found")
    
    # 6. Validate genres
    if 'genres' in movies_clean.columns:
        valid_genres = {
            'Action', 'Adventure', 'Animation', 'Children\'s', 'Comedy', 
            'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 
            'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 
            'Thriller', 'War', 'Western', '(no genres listed)'
        }
        
        # Check for movies with no genres
        no_genres = (movies_clean['genres'] == '(no genres listed)').sum()
        print(f"✓ Found {no_genres} movies with no genres listed")
        
        # Check for empty genres
        empty_genres = (movies_clean['genres'] == '').sum()
        if empty_genres > 0:
            print(f"✓ Found {empty_genres} movies with empty genres")
        

    
    return movies_clean

# Apply cleaning
movies = cleaning_movies_data(movies)

print("\n" + "=" * 50)
print("PROCESSING SUMMARY")
print("=" * 50)
print(f"Total movies: {len(movies)}")
print(f"Columns: {list(movies.columns)}")

if 'release_date_year' in movies.columns:
    print(f"Release year range: {movies['release_date_year'].min()} - {movies['release_date_year'].max()}")

if 'genres' in movies.columns:
    print(f"Movies with no genres: {(movies['genres'] == '(no genres listed)').sum()}")
    print(f"Unique genre combinations: {movies['genres'].nunique()}")

MOVIES DATA CLEANING PROCESS
==================================================
✓ Removed columns: ['video_release_date', 'IMDb_URL', 'unknown']
✓ No duplicate movies found
✓ Found missing values: {'movieId': np.int64(0), 'title': np.int64(0), 'release_date': np.int64(1), 'Action': np.int64(0), 'Adventure': np.int64(0), 'Animation': np.int64(0), "Children's": np.int64(0), 'Comedy': np.int64(0), 'Crime': np.int64(0), 'Documentary': np.int64(0), 'Drama': np.int64(0), 'Fantasy': np.int64(0), 'Film-Noir': np.int64(0), 'Horror': np.int64(0), 'Musical': np.int64(0), 'Mystery': np.int64(0), 'Romance': np.int64(0), 'Sci-Fi': np.int64(0), 'Thriller': np.int64(0), 'War': np.int64(0), 'Western': np.int64(0)}
✓ Removed 1 rows with missing values
✓ All dates are valid
✓ All release years are valid (≥ 1900)
✓ Found 1677 titles with year in parentheses
✓ Modified 1681 titles (lowercase + removed years)

==================================================
PROCESSING SUMMARY
==================================================
Total movies: 1681
Columns: ['movieId', 'title', 'release_date', 'Action', 'Adventure', 'Animation', "Children's", 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western', 'release_date_year', 'release_date_month']
Release year range: 1922 - 1998

In [52]:
movies.describe().T

,count,mean,min,25%,50%,75%,max,std
movieId,1681.0,841.841761,1.0,422.0,842.0,1262.0,1682.0,485.638077
release_date,1681,1989-07-16 12:53:32.373587072,1922-01-01 00:00:00,1993-01-01 00:00:00,1995-01-01 00:00:00,1996-10-18 00:00:00,1998-10-23 00:00:00,NaN
Action,1681.0,0.149316,0.0,0.0,0.0,0.0,1.0,0.356506
Adventure,1681.0,0.080309,0.0,0.0,0.0,0.0,1.0,0.271852
Animation,1681.0,0.024985,0.0,0.0,0.0,0.0,1.0,0.156126
Children's,1681.0,0.072576,0.0,0.0,0.0,0.0,1.0,0.259516
Comedy,1681.0,0.300416,0.0,0.0,0.0,1.0,1.0,0.458576
Crime,1681.0,0.064842,0.0,0.0,0.0,0.0,1.0,0.246321
Documentary,1681.0,0.029744,0.0,0.0,0.0,0.0,1.0,0.169931
Drama,1681.0,0.431291,0.0,0.0,0.0,1.0,1.0,0.495404
Fantasy,1681.0,0.013087,0.0,0.0,0.0,0.0,1.0,0.113683
Film-Noir,1681.0,0.014277,0.0,0.0,0.0,0.0,1.0,0.118667
Horror,1681.0,0.054729,0.0,0.0,0.0,0.0,1.0,0.227519
Musical,1681.0,0.033314,0.0,0.0,0.0,0.0,1.0,0.179507
Mystery,1681.0,0.036288,0.0,0.0,0.0,0.0,1.0,0.187061
Romance,1681.0,0.146936,0.0,0.0,0.0,0.0,1.0,0.354148
Sci-Fi,1681.0,0.060083,0.0,0.0,0.0,0.0,1.0,0.237712
Thriller,1681.0,0.149316,0.0,0.0,0.0,0.0,1.0,0.356506
War,1681.0,0.042237,0.0,0.0,0.0,0.0,1.0,0.201189
Western,1681.0,0.016062,0.0,0.0,0.0,0.0,1.0,0.125751
release_date_year,1681.0,1989.38608,1922.0,1993.0,1995.0,1996.0,1998.0,14.25358
release_date_month,1681.0,2.669839,1.0,1.0,1.0,3.0,12.0,3.014031

In [53]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1681 entries, 0 to 1681
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   movieId             1681 non-null   int64
 1   title               1681 non-null   object
 2   release_date        1681 non-null   datetime64[ns]
 3   Action              1681 non-null   int64
 4   Adventure           1681 non-null   int64
 5   Animation           1681 non-null   int64
 6   Children's          1681 non-null   int64
 7   Comedy              1681 non-null   int64
 8   Crime               1681 non-null   int64
 9   Documentary         1681 non-null   int64
 10  Drama               1681 non-null   int64
 11  Fantasy             1681 non-null   int64
 12  Film-Noir           1681 non-null   int64
 13  Horror              1681 non-null   int64
 14  Musical             1681 non-null   int64
 15  Mystery             1681 non-null   int64
 16  Romance             1681 non-null   int64
 17  Sci-Fi              1681 non-null   int64
 18  Thriller            1681 non-null   int64
 19  War                 1681 non-null   int64
 20  Western             1681 non-null   int64
 21  release_date_year   1681 non-null   int32
 22  release_date_month  1681 non-null   int32
dtypes: datetime64[ns](1), int32(2), int64(19), object(1)
memory usage: 302.1+ KB

<a class="anchor" id='lib'></a>
<font color = '#008000'>

## **2.3. Users** </font>

In [54]:
users.head()

   userId  age gender  occupation zip_code
0       1   24      M  technician    85711
1       2   53      F       other    94043
2       3   23      M      writer    32067
3       4   24      M  technician    43537
4       5   33      F       other    15213

In [55]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   userId      943 non-null    int64
 1   age         943 non-null    int64
 2   gender      943 non-null    object
 3   occupation  943 non-null    object
 4   zip_code    943 non-null    object
dtypes: int64(2), object(3)
memory usage: 37.0+ KB

In [56]:
#frequency distribution of all categorical columns
for col in users.select_dtypes(include=['object', 'category']).columns:
    print()
    print(f"--- {col} ---")
    display(users[col].value_counts())

--- gender ---

gender
M    670
F    273
Name: count, dtype: int64

--- occupation ---

occupation
student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
lawyer            12
salesman          12
none               9
homemaker          7
doctor             7
Name: count, dtype: int64

--- zip_code ---

zip_code
55414    9
55105    6
10003    5
20009    5
55337    5
        ..
55038    1
33319    1
97229    1
78209    1
06405    1
Name: count, Length: 795, dtype: int64

In [57]:
valid_occupations = [
    'administrator', 'artist', 'doctor', 'educator', 'engineer', 'entertainment',
    'executive', 'healthcare', 'homemaker', 'lawyer', 'librarian', 'marketing',
    'none', 'other', 'programmer', 'retired', 'salesman', 'scientist', 'student',
    'technician', 'writer'
]

In [58]:
def cleaning_users_data(df, valid_occupations):
    # Clean column names
    df.columns = ['user_id', 'age', 'gender', 'occupation', 'zip_code']
    
    # Store original count for reporting
    original_count = len(df)
    
    # Remove invalid ages (5-100)
    df = df[df['age'].between(5, 100)]
    age_removed = original_count - len(df)
    
    # Remove invalid genders (only M/F)
    df = df[df['gender'].isin(['M', 'F'])]
    gender_removed = original_count - len(df) - age_removed
    
    # Convert gender to dummy variables
    df['gender'] = df['gender'].map({'M': 1, 'F': 0})
    
    # Convert occupation to lowercase for consistency
    df['occupation'] = df['occupation'].str.lower()
    
    # Check for occupation mismatches
    invalid_occupations = df[~df['occupation'].isin(valid_occupations)]
    occupation_removed = len(invalid_occupations)
    
    # Remove invalid occupations
    df = df[df['occupation'].isin(valid_occupations)]
    
    # Store results for reporting
    cleaning_info = {
        'original_count': original_count,
        'age_removed': age_removed,
        'gender_removed': gender_removed,
        'occupation_removed': occupation_removed,
        'invalid_occupations_found': invalid_occupations['occupation'].unique().tolist() if occupation_removed > 0 else []
    }
    
    return df, cleaning_info

users, cleaning_info = cleaning_users_data(users, valid_occupations)

In [59]:
users

     user_id  age  gender     occupation zip_code
0          1   24       1     technician    85711
1          2   53       0          other    94043
2          3   23       1         writer    32067
3          4   24       1     technician    43537
4          5   33       0          other    15213
..       ...  ...     ...            ...      ...
938      939   26       0        student    33319
939      940   32       1  administrator    02215
940      941   20       1        student    97229
941      942   48       0      librarian    78209
942      943   22       1        student    77841

[943 rows x 5 columns]

In [60]:
# Display the processing report
print("OCCUPATION VALIDATION REPORT")
print("=" * 50)
print(f"Original users: {cleaning_info['original_count']}")
print(f"Removed due to invalid age: {cleaning_info['age_removed']}")
print(f"Removed due to invalid gender: {cleaning_info['gender_removed']}")
print(f"Removed due to invalid occupation: {cleaning_info['occupation_removed']}")

if cleaning_info['invalid_occupations_found']:
    print(f"Invalid occupations found: {cleaning_info['invalid_occupations_found']}")
else:
    print("✅ All occupations matched perfectly!")

print(f"Final users: {len(users)}")

print("\n" + "=" * 50)
print("PROCESSED USERS TABLE")
print("=" * 50)
print(users.head())

print("\n" + "=" * 50)
print("FINAL SUMMARY")
print("=" * 50)
print(f"Total users: {len(users)}")
print(f"Columns: {list(users.columns)}")
print(f"Age range: {users['age'].min()} - {users['age'].max()}")
print(f"Gender distribution: {users['gender'].value_counts().to_dict()}")
print(f"Unique occupations: {users['occupation'].nunique()}")
print(f"All occupations: {sorted(users['occupation'].unique().tolist())}")

OCCUPATION VALIDATION REPORT
==================================================
Original users: 943
Removed due to invalid age: 0
Removed due to invalid gender: 0
Removed due to invalid occupation: 0
✅ All occupations matched perfectly!
Final users: 943

==================================================
PROCESSED USERS TABLE
==================================================
   user_id  age  gender  occupation zip_code
0        1   24       1  technician    85711
1        2   53       0       other    94043
2        3   23       1      writer    32067
3        4   24       1  technician    43537
4        5   33       0       other    15213

==================================================
FINAL SUMMARY
==================================================
Total users: 943
Columns: ['user_id', 'age', 'gender', 'occupation', 'zip_code']
Age range: 7 - 73
Gender distribution: {1: 670, 0: 273}
Unique occupations: 21
All occupations: ['administrator', 'artist', 'doctor', 'educator', 'engineer', 'entertainment', 'executive', 'healthcare', 'homemaker', 'lawyer', 'librarian', 'marketing', 'none', 'other', 'programmer', 'retired', 'salesman', 'scientist', 'student', 'technician', 'writer']

<a class="anchor" id='lib'></a>
<font color = '#008000'>

## **2.4. Genres** </font>

In [61]:
genres.head()

        genre  genreId
0     unknown        0
1      Action        1
2   Adventure        2
3   Animation        3
4  Children's        4

In [62]:
genres.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   genre    19 non-null     object
 1   genreId  19 non-null     int64
dtypes: int64(1), object(1)
memory usage: 436.0+ bytes

In [63]:
def cleaning_genres_data(df):
    # Store original info for reporting
    original_count = len(df)
    original_columns = list(df.columns)
    
    # Remove empty columns
    columns_to_remove = []
    for column in df.columns:
        if len(df[column].value_counts()) == 0:
            columns_to_remove.append(column)
    
    # Remove all identified empty columns
    if columns_to_remove:
        df.drop(columns_to_remove, axis=1, inplace=True)
    
    # Remove duplicates
    duplicates_count = df.duplicated().sum()
    df = df.drop_duplicates()
    
    # Store cleaning info for reporting
    cleaning_info = {
        'original_count': original_count,
        'original_columns': original_columns,
        'columns_removed': columns_to_remove,
        'duplicates_removed': duplicates_count,
        'final_count': len(df),
        'final_columns': list(df.columns)
    }
    
    return df, cleaning_info

genres, cleaning_info = cleaning_genres_data(genres)

In [64]:
# Display the processing report
print("GENRES CLEANING REPORT")
print("=" * 50)
print(f"Original entries: {cleaning_info['original_count']}")
print(f"Final entries: {cleaning_info['final_count']}")
print(f"Duplicates removed: {cleaning_info['duplicates_removed']}")

if cleaning_info['columns_removed']:
    print(f"Empty columns removed: {cleaning_info['columns_removed']}")
else:
    print("No empty columns removed")

print(f"Original columns: {cleaning_info['original_columns']}")
print(f"Final columns: {cleaning_info['final_columns']}")

print("\n" + "=" * 50)
print("PROCESSED GENRES TABLE")
print("=" * 50)
print(genres.head())

print("\n" + "=" * 50)
print("FINAL SUMMARY")
print("=" * 50)
print(f"Total genres: {len(genres)}")
print(f"Sample genres: {genres.iloc[:, 0].head(10).tolist()}")

GENRES CLEANING REPORT
==================================================
Original entries: 19
Final entries: 19
Duplicates removed: 0
No empty columns removed
Original columns: ['genre', 'genreId']
Final columns: ['genre', 'genreId']

==================================================
PROCESSED GENRES TABLE
==================================================
        genre  genreId
0     unknown        0
1      Action        1
2   Adventure        2
3   Animation        3
4  Children's        4

==================================================
FINAL SUMMARY
==================================================
Total genres: 19
Sample genres: ['unknown', 'Action', 'Adventure', 'Animation', "Children's", 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy']

<a class="anchor" id='lib'></a>
<font color = '#008000'>

## **2.5. Occupations** </font>

In [65]:
occupations.head()

      occupation
0  administrator
1         artist
2         doctor
3       educator
4       engineer

In [66]:
occupations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   occupation  21 non-null     object
dtypes: object(1)
memory usage: 300.0+ bytes

In [67]:
occupations['occupation'].values

array(['administrator', 'artist', 'doctor', 'educator', 'engineer',
       'entertainment', 'executive', 'healthcare', 'homemaker', 'lawyer',
       'librarian', 'marketing', 'none', 'other', 'programmer', 'retired',
       'salesman', 'scientist', 'student', 'technician', 'writer'],
      dtype=object)

In [68]:
def cleaning_occupations_data(df):
    # Store original info for reporting
    original_count = len(df)
    original_columns = list(df.columns)
    
    # Remove empty columns
    columns_to_remove = []
    for column in df.columns:
        if len(df[column].value_counts()) == 0:
            columns_to_remove.append(column)
    
    # Remove all identified empty columns
    if columns_to_remove:
        df.drop(columns_to_remove, axis=1, inplace=True)
    
    # Remove duplicates
    duplicates_count = df.duplicated().sum()
    df = df.drop_duplicates()
    
    # Store cleaning info for reporting
    cleaning_info = {
        'original_count': original_count,
        'original_columns': original_columns,
        'columns_removed': columns_to_remove,
        'duplicates_removed': duplicates_count,
        'final_count': len(df),
        'final_columns': list(df.columns)
    }
    
    return df, cleaning_info

occupations, cleaning_info = cleaning_occupations_data(occupations)

In [69]:
# Display the processing report
print("OCCUPATIONS CLEANING REPORT")
print("=" * 50)
print(f"Original entries: {cleaning_info['original_count']}")
print(f"Final entries: {cleaning_info['final_count']}")
print(f"Duplicates removed: {cleaning_info['duplicates_removed']}")

if cleaning_info['columns_removed']:
    print(f"Empty columns removed: {cleaning_info['columns_removed']}")
else:
    print("No empty columns removed")

print(f"Original columns: {cleaning_info['original_columns']}")
print(f"Final columns: {cleaning_info['final_columns']}")

print("\n" + "=" * 50)
print("PROCESSED OCCUPATIONS TABLE")
print("=" * 50)
print(occupations.head())

print("\n" + "=" * 50)
print("FINAL SUMMARY")
print("=" * 50)
print(f"Total occupations: {len(occupations)}")
print(f"All occupations: {occupations.iloc[:, 0].tolist()}")

OCCUPATIONS CLEANING REPORT
==================================================
Original entries: 21
Final entries: 21
Duplicates removed: 0
No empty columns removed
Original columns: ['occupation']
Final columns: ['occupation']

==================================================
PROCESSED OCCUPATIONS TABLE
==================================================
      occupation
0  administrator
1         artist
2         doctor
3       educator
4       engineer

==================================================
FINAL SUMMARY
==================================================
Total occupations: 21
All occupations: ['administrator', 'artist', 'doctor', 'educator', 'engineer', 'entertainment', 'executive', 'healthcare', 'homemaker', 'lawyer', 'librarian', 'marketing', 'none', 'other', 'programmer', 'retired', 'salesman', 'scientist', 'student', 'technician', 'writer']

<a class="anchor" id='import'>
<font color = '#006400'>
    
# **3. Convert to Parquet** </font>
</a>

In [70]:
# Define paths
output_dir = "../results"

# Make sure the directory exists
import os
os.makedirs(output_dir, exist_ok=True)

# Convert and save
ratings.to_parquet(os.path.join(output_dir, "ratings100k.parquet"), index=False)
movies.to_parquet(os.path.join(output_dir, "movies100k.parquet"), index=False)
users.to_parquet(os.path.join(output_dir, "users100k.parquet"), index=False)
genres.to_parquet(os.path.join(output_dir, "genres100k.parquet"), index=False)
occupations.to_parquet(os.path.join(output_dir, "occupations100k.parquet"), index=False)