<a class="anchor" id='import'>
<font color = '#006400'>
    
# **1. Data Integration** </font>
</a>

<a class="anchor" id='lib'></a>
<font color = '#008000'>

## **1.1. Import the needed libraries** </font>

In [133]:
import pandas as pd

<a class="anchor" id='lib'></a>
<font color = '#008000'>

## **1.2. Integrate the datasets into the notebook** </font>

In [134]:
#Import u.data dataset
ratings_path = "/Users/goncalobento/Downloads/ml-100k/u.data"
columns = ['userId', 'movieId', 'rating', 'timestamp']

ratings = pd.read_csv(ratings_path, sep='\t', names=columns)

In [135]:
#Import u.item dataset
items_path = "/Users/goncalobento/Downloads/ml-100k/u.item"

item_columns = [
    'movieId', 'title', 'release_date', 'video_release_date', 'IMDb_URL',
    'unknown', 'Action', 'Adventure', 'Animation', "Children's", 'Comedy',
    'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror',
    'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western'
]

movies = pd.read_csv(items_path, sep='|', names=item_columns, encoding='latin-1')

In [136]:
#Import u.user dataset
users_path = "/Users/goncalobento/Downloads/ml-100k/u.user"

user_columns = ['userId', 'age', 'gender', 'occupation', 'zip_code']

users = pd.read_csv(users_path, sep='|', names=user_columns)

In [137]:
#Import u.genre dataset
genre_path = "/Users/goncalobento/Downloads/ml-100k/u.genre"

genre_columns = ['genre', 'genreId']

genres = pd.read_csv(genre_path, sep='|', names=genre_columns, encoding='latin-1')

In [138]:
#Import u.occupation dataset
occupation_path = "/Users/goncalobento/Downloads/ml-100k/u.occupation"

occupations = pd.read_csv(occupation_path, names=['occupation'], encoding='latin-1')

<a class="anchor" id='import'>
<font color = '#006400'>
    
# **2. Data Access, Exploration and Understanding** </font>
</a>

<a class="anchor" id='lib'></a>
<font color = '#008000'>

## **2.1. Ratings** </font>

In [139]:
ratings['rating_date'] = pd.to_datetime(ratings['timestamp'], unit='s')
ratings['ratings_date_year']=ratings['rating_date'].dt.year
ratings

,userId,movieId,rating,timestamp,rating_date,ratings_date_year
0,196,242,3,881250949,1997-12-04 15:55:49,1997
1,186,302,3,891717742,1998-04-04 19:22:22,1998
2,22,377,1,878887116,1997-11-07 07:18:36,1997
3,244,51,2,880606923,1997-11-27 05:02:03,1997
4,166,346,1,886397596,1998-02-02 05:33:16,1998
...,...,...,...,...,...,...
99995,880,476,3,880175444,1997-11-22 05:10:44,1997
99996,716,204,5,879795543,1997-11-17 19:39:03,1997
99997,276,1090,1,874795795,1997-09-20 22:49:55,1997
99998,13,225,2,882399156,1997-12-17 22:52:36,1997
99999,12,203,3,879959583,1997-11-19 17:13:03,1997

In [140]:
user_ratings = ratings[ratings['userId'] == 196]

In [141]:
user_ratings[user_ratings['movieId'].duplicated()]

Empty DataFrame
Columns: [userId, movieId, rating, timestamp, rating_date, ratings_date_year]
Index: []

In [142]:
ratings.head()

   userId  movieId  rating  timestamp         rating_date  ratings_date_year
0     196      242       3  881250949 1997-12-04 15:55:49               1997
1     186      302       3  891717742 1998-04-04 19:22:22               1998
2      22      377       1  878887116 1997-11-07 07:18:36               1997
3     244       51       2  880606923 1997-11-27 05:02:03               1997
4     166      346       1  886397596 1998-02-02 05:33:16               1998

In [143]:
ratings.describe()

,userId,movieId,rating,timestamp,rating_date,ratings_date_year
count,100000.00000,100000.000000,100000.000000,1.000000e+05,100000,100000.000000
mean,462.48475,425.530130,3.529860,8.835289e+08,1997-12-31 00:40:51.488619904,1997.471010
min,1.00000,1.000000,1.000000,8.747247e+08,1997-09-20 03:05:10,1997.000000
25%,254.00000,175.000000,3.000000,8.794487e+08,1997-11-13 19:18:29.500000,1997.000000
50%,447.00000,322.000000,4.000000,8.828269e+08,1997-12-22 21:42:24,1997.000000
75%,682.00000,631.000000,4.000000,8.882600e+08,1998-02-23 18:53:04,1998.000000
max,943.00000,1682.000000,5.000000,8.932866e+08,1998-04-22 23:10:38,1998.000000
std,266.61442,330.798356,1.125674,5.343856e+06,NaN,0.499161

In [144]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 6 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   userId             100000 non-null  int64
 1   movieId            100000 non-null  int64
 2   rating             100000 non-null  int64
 3   timestamp          100000 non-null  int64
 4   rating_date        100000 non-null  datetime64[ns]
 5   ratings_date_year  100000 non-null  int32
dtypes: datetime64[ns](1), int32(1), int64(4)
memory usage: 4.2 MB

In [145]:
ratings.head()

   userId  movieId  rating  timestamp         rating_date  ratings_date_year
0     196      242       3  881250949 1997-12-04 15:55:49               1997
1     186      302       3  891717742 1998-04-04 19:22:22               1998
2      22      377       1  878887116 1997-11-07 07:18:36               1997
3     244       51       2  880606923 1997-11-27 05:02:03               1997
4     166      346       1  886397596 1998-02-02 05:33:16               1998

In [146]:
ratings[ratings.duplicated()]

Empty DataFrame
Columns: [userId, movieId, rating, timestamp, rating_date, ratings_date_year]
Index: []

<a class="anchor" id='lib'></a>
<font color = '#008000'>

## **2.2. Movies** </font>

In [161]:
pd.to_datetime(movies['release_date'], format='%d-%b-%Y', errors='coerce')

0      1995-01-01
1      1995-01-01
2      1995-01-01
3      1995-01-01
4      1995-01-01
          ...
1677   1998-02-06
1678   1998-02-06
1679   1998-01-01
1680   1994-01-01
1681   1996-03-08
Name: release_date, Length: 1682, dtype: datetime64[ns]

In [170]:
len(movies['video_release_date'].value_counts())

0

In [169]:
movies.columns

Index(['movieId', 'title', 'release_date', 'video_release_date', 'IMDb_URL',
       'unknown', 'Action', 'Adventure', 'Animation', 'Children's', 'Comedy',
       'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror',
       'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War',
       'Western'],
      dtype='object')

In [147]:
movies['title']=movies['title'].str.lower()
movies

,movieId,title,release_date,video_release_date,IMDb_URL,unknown,Action,Adventure,Animation,Children's,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,toy story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,goldeneye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,four rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,get shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1678,mat' i syn (1997),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?Mat%27+i+syn+...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1678,1679,b. monkey (1998),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?B%2E+Monkey+(...,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
1679,1680,sliding doors (1998),01-Jan-1998,NaN,http://us.imdb.com/Title?Sliding+Doors+(1998),0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1680,1681,you so crazy (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?You%20So%20Cr...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1681,1682,scream of stone (schrei aus stein) (1991),08-Mar-1996,NaN,http://us.imdb.com/M/title-exact?Schrei%20aus%...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [148]:
movies['release_date'] = pd.to_datetime(movies['release_date'])

In [149]:
movies.head()

,movieId,title,release_date,video_release_date,IMDb_URL,unknown,Action,Adventure,Animation,Children's,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,toy story (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,goldeneye (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,four rooms (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,get shorty (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,copycat (1995),1995-01-01,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [150]:
movies.describe().T

,count,mean,min,25%,50%,75%,max,std
movieId,1682.0,841.5,1.0,421.25,841.5,1261.75,1682.0,485.695893
release_date,1681,1989-07-16 12:53:32.373587072,1922-01-01 00:00:00,1993-01-01 00:00:00,1995-01-01 00:00:00,1996-10-18 00:00:00,1998-10-23 00:00:00,NaN
video_release_date,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
unknown,1682.0,0.001189,0.0,0.0,0.0,0.0,1.0,0.034473
Action,1682.0,0.149227,0.0,0.0,0.0,0.0,1.0,0.356418
Adventure,1682.0,0.080262,0.0,0.0,0.0,0.0,1.0,0.271779
Animation,1682.0,0.02497,0.0,0.0,0.0,0.0,1.0,0.156081
Children's,1682.0,0.072533,0.0,0.0,0.0,0.0,1.0,0.259445
Comedy,1682.0,0.300238,0.0,0.0,0.0,1.0,1.0,0.458498
Crime,1682.0,0.064804,0.0,0.0,0.0,0.0,1.0,0.246253
Documentary,1682.0,0.029727,0.0,0.0,0.0,0.0,1.0,0.169882
Drama,1682.0,0.431034,0.0,0.0,0.0,1.0,1.0,0.495368
Fantasy,1682.0,0.01308,0.0,0.0,0.0,0.0,1.0,0.11365
Film-Noir,1682.0,0.014269,0.0,0.0,0.0,0.0,1.0,0.118632
Horror,1682.0,0.054697,0.0,0.0,0.0,0.0,1.0,0.227455
Musical,1682.0,0.033294,0.0,0.0,0.0,0.0,1.0,0.179456
Mystery,1682.0,0.036266,0.0,0.0,0.0,0.0,1.0,0.187008
Romance,1682.0,0.146849,0.0,0.0,0.0,0.0,1.0,0.354061
Sci-Fi,1682.0,0.060048,0.0,0.0,0.0,0.0,1.0,0.237646
Thriller,1682.0,0.149227,0.0,0.0,0.0,0.0,1.0,0.356418
War,1682.0,0.042212,0.0,0.0,0.0,0.0,1.0,0.201131
Western,1682.0,0.016052,0.0,0.0,0.0,0.0,1.0,0.125714

In [151]:
movies[movies.duplicated()]

Empty DataFrame
Columns: [movieId, title, release_date, video_release_date, IMDb_URL, unknown, Action, Adventure, Animation, Children's, Comedy, Crime, Documentary, Drama, Fantasy, Film-Noir, Horror, Musical, Mystery, Romance, Sci-Fi, Thriller, War, Western]
Index: []

[0 rows x 24 columns]

In [152]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1682 entries, 0 to 1681
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   movieId             1682 non-null   int64
 1   title               1682 non-null   object
 2   release_date        1681 non-null   datetime64[ns]
 3   video_release_date  0 non-null      float64
 4   IMDb_URL            1679 non-null   object
 5   unknown             1682 non-null   int64
 6   Action              1682 non-null   int64
 7   Adventure           1682 non-null   int64
 8   Animation           1682 non-null   int64
 9   Children's          1682 non-null   int64
 10  Comedy              1682 non-null   int64
 11  Crime               1682 non-null   int64
 12  Documentary         1682 non-null   int64
 13  Drama               1682 non-null   int64
 14  Fantasy             1682 non-null   int64
 15  Film-Noir           1682 non-null   int64
 16  Horror              1682 non-null   int64
 17  Musical             1682 non-null   int64
 18  Mystery             1682 non-null   int64
 19  Romance             1682 non-null   int64
 20  Sci-Fi              1682 non-null   int64
 21  Thriller            1682 non-null   int64
 22  War                 1682 non-null   int64
 23  Western             1682 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(20), object(2)
memory usage: 315.5+ KB

<a class="anchor" id='lib'></a>
<font color = '#008000'>

## **2.3. Users** </font>

In [153]:
users.head()

   userId  age gender  occupation zip_code
0       1   24      M  technician    85711
1       2   53      F       other    94043
2       3   23      M      writer    32067
3       4   24      M  technician    43537
4       5   33      F       other    15213

In [154]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   userId      943 non-null    int64
 1   age         943 non-null    int64
 2   gender      943 non-null    object
 3   occupation  943 non-null    object
 4   zip_code    943 non-null    object
dtypes: int64(2), object(3)
memory usage: 37.0+ KB

In [155]:
for col in users.select_dtypes(include=['object', 'category']).columns:
    print()
    print(f"--- {col} ---")
    display(users[col].value_counts())

--- gender ---

gender
M    670
F    273
Name: count, dtype: int64

--- occupation ---

occupation
student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
lawyer            12
salesman          12
none               9
homemaker          7
doctor             7
Name: count, dtype: int64

--- zip_code ---

zip_code
55414    9
55105    6
55337    5
10003    5
20009    5
        ..
24060    1
55413    1
19149    1
02176    1
77841    1
Name: count, Length: 795, dtype: int64

<a class="anchor" id='lib'></a>
<font color = '#008000'>

## **2.4. Genres** </font>

In [156]:
genres.head()

        genre  genreId
0     unknown        0
1      Action        1
2   Adventure        2
3   Animation        3
4  Children's        4

In [157]:
genres.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   genre    19 non-null     object
 1   genreId  19 non-null     int64
dtypes: int64(1), object(1)
memory usage: 436.0+ bytes

<a class="anchor" id='lib'></a>
<font color = '#008000'>

## **2.5. Occupations** </font>

In [158]:
occupations.head()

      occupation
0  administrator
1         artist
2         doctor
3       educator
4       engineer

In [159]:
occupations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   occupation  21 non-null     object
dtypes: object(1)
memory usage: 300.0+ bytes

In [160]:
occupations['occupation'].values

array(['administrator', 'artist', 'doctor', 'educator', 'engineer',
       'entertainment', 'executive', 'healthcare', 'homemaker', 'lawyer',
       'librarian', 'marketing', 'none', 'other', 'programmer', 'retired',
       'salesman', 'scientist', 'student', 'technician', 'writer'],
      dtype=object)