<a class="anchor" id='import'>
<font color = '#006400'>
    
# **1. Data Integration** </font>
</a>

<a class="anchor" id='lib'></a>
<font color = '#008000'>

## **1.1. Import the needed libraries** </font>

In [1]:
import polars as pl
import requests
import zipfile
import io
import pandas as pd

<a class="anchor" id='lib'></a>
<font color = '#008000'>

## **1.2. Integrate the datasets into the notebook** </font>

In [2]:
url_data = "https://files.grouplens.org/datasets/movielens/ml-32m.zip"

response = requests.get(url_data, verify=False)
zip_file = zipfile.ZipFile(io.BytesIO(response.content))

with zip_file.open("ml-32m/movies.csv") as f:
    movies = pd.read_csv(f)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'files.grouplens.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [3]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [4]:
url_data = "https://files.grouplens.org/datasets/movielens/ml-32m.zip"
response = requests.get(url_data, verify=False)
zip_file = zipfile.ZipFile(io.BytesIO(response.content))

with zip_file.open("ml-32m/ratings.csv") as f:
    ratings = pd.read_csv(f)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'files.grouplens.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [5]:
ratings.head()

   userId  movieId  rating  timestamp
0       1       17     4.0  944249077
1       1       25     1.0  944250228
2       1       29     2.0  943230976
3       1       30     5.0  944249077
4       1       32     5.0  943228858

In [6]:
url_data = "https://files.grouplens.org/datasets/movielens/ml-32m.zip"
response = requests.get(url_data, verify=False)
zip_file = zipfile.ZipFile(io.BytesIO(response.content))

with zip_file.open("ml-32m/links.csv") as f:
    links = pd.read_csv(f)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'files.grouplens.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [7]:
links.head()

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [8]:
url_data = "https://files.grouplens.org/datasets/movielens/ml-32m.zip"
response = requests.get(url_data, verify=False)
zip_file = zipfile.ZipFile(io.BytesIO(response.content))

with zip_file.open("ml-32m/tags.csv") as f:
    tags = pd.read_csv(f)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'files.grouplens.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [9]:
tags.head()

   userId  movieId          tag   timestamp
0      22    26479  Kevin Kline  1583038886
1      22    79592     misogyny  1581476297
2      22   247150   acrophobia  1622483469
3      34     2174        music  1249808064
4      34     2174        weird  1249808102

<a class="anchor" id='import'>
<font color = '#006400'>
    
# **2. Data Access, Exploration and Understanding** </font>
</a>

<a class="anchor" id='lib'></a>
<font color = '#008000'>

## **2.1. Ratings** </font>

In [10]:
ratings.describe()

             userId       movieId        rating     timestamp
count  3.200020e+07  3.200020e+07  3.200020e+07  3.200020e+07
mean   1.002785e+05  2.931861e+04  3.540396e+00  1.275241e+09
std    5.794905e+04  5.095816e+04  1.058986e+00  2.561630e+08
min    1.000000e+00  1.000000e+00  5.000000e-01  7.896520e+08
25%    5.005300e+04  1.233000e+03  3.000000e+00  1.051012e+09
50%    1.002970e+05  3.452000e+03  3.500000e+00  1.272622e+09
75%    1.504510e+05  4.419900e+04  4.000000e+00  1.503158e+09
max    2.009480e+05  2.927570e+05  5.000000e+00  1.697164e+09

In [11]:
ratings["movieId"].unique()
ratings["userId"].unique()
ratings["rating"].unique()

array([4. , 1. , 2. , 5. , 3. , 3.5, 0.5, 4.5, 2.5, 1.5])

<a class="anchor" id='lib'></a>
<font color = '#008000'>

## **2.2. Movies** </font>

In [12]:
movies.describe()

             movieId
count   87585.000000
mean   157651.365519
std     79013.402099
min         1.000000
25%    112657.000000
50%    165741.000000
75%    213203.000000
max    292757.000000

In [13]:
movies.filter(pl.col('movieId') == 29).select('genres')

TypeError: Index(...) must be called with a collection of some kind, <Expr ['[(col("movieId")) == (dyn int:…'] at 0x12A958D60> was passed

In [ ]:
movies.filter(pl.col('genres') == 'no genres listed')

TypeError: Index(...) must be called with a collection of some kind, <Expr ['[(col("genres")) == ("no genre…'] at 0x13E06FF10> was passed

In [ ]:
valid_genres = [
    "Action",
    "Adventure",
    "Animation",
    "Children's",
    "Comedy",
    "Crime",
    "Documentary",
    "Drama",
    "Fantasy",
    "Film-Noir",
    "Horror",
    "Musical",
    "Mystery",
    "Romance",
    "Sci-Fi",
    "Thriller",
    "War",
    "Western",
    "(no genres listed)"
]


invalid_genres = (
    movies
    .select(pl.col("genres").str.split('|').explode())
    .filter(~pl.col("genres").is_in(valid_genres))
    .unique()
)

print(invalid_genres)

AttributeError: 'DataFrame' object has no attribute 'select'

In [ ]:
movies.filter(pl.col('genres') == 'IMAX')

shape: (0, 3)
┌─────────┬───────┬────────┐
│ movieId ┆ title ┆ genres │
│ ---     ┆ ---   ┆ ---    │
│ i64     ┆ str   ┆ str    │
╞═════════╪═══════╪════════╡
└─────────┴───────┴────────┘

In [ ]:
invalid_genres = ["IMAX",  "(no genres listed)"]
movies = movies.filter(~pl.col("genres").is_in(invalid_genres))

In [ ]:
movies.describe()

shape: (9, 4)
┌────────────┬───────────────┬───────────────┬─────────┐
│ statistic  ┆ movieId       ┆ title         ┆ genres  │
│ ---        ┆ ---           ┆ ---           ┆ ---     │
│ str        ┆ f64           ┆ str           ┆ str     │
╞════════════╪═══════════════╪═══════════════╪═════════╡
│ count      ┆ 80504.0       ┆ 80504         ┆ 80504   │
│ null_count ┆ 0.0           ┆ 0             ┆ 0       │
│ mean       ┆ 155501.531576 ┆ null          ┆ null    │
│ std        ┆ 81084.239109  ┆ null          ┆ null    │
│ min        ┆ 1.0           ┆  (2019)       ┆ Action  │
│ 25%        ┆ 104285.0      ┆ null          ┆ null    │
│ 50%        ┆ 164739.0      ┆ null          ┆ null    │
│ 75%        ┆ 213756.0      ┆ null          ┆ null    │
│ max        ┆ 292757.0      ┆ 貞子3D (2012) ┆ Western │
└────────────┴───────────────┴───────────────┴─────────┘

In [ ]:
movies = movies.with_columns(
    pl.col("title").str.replace(r" \(\d{4}\)$", "", literal=False).alias("title")
)

In [ ]:
movies.head(1000)

shape: (1_000, 3)
┌─────────┬──────────────────────────────┬─────────────────────────────────┐
│ movieId ┆ title                        ┆ genres                          │
│ ---     ┆ ---                          ┆ ---                             │
│ i64     ┆ str                          ┆ str                             │
╞═════════╪══════════════════════════════╪═════════════════════════════════╡
│ 1       ┆ Toy Story                    ┆ Adventure|Animation|Children|C… │
│ 2       ┆ Jumanji                      ┆ Adventure|Children|Fantasy      │
│ 3       ┆ Grumpier Old Men             ┆ Comedy|Romance                  │
│ 4       ┆ Waiting to Exhale            ┆ Comedy|Drama|Romance            │
│ 5       ┆ Father of the Bride Part II  ┆ Comedy                          │
│ …       ┆ …                            ┆ …                               │
│ 1018    ┆ That Darn Cat!               ┆ Children|Comedy|Mystery         │
│ 1019    ┆ 20,000 Leagues Under the Sea ┆ Adventure|Drama|Sci-Fi          │
│ 1020    ┆ Cool Runnings                ┆ Comedy                          │
│ 1021    ┆ Angels in the Outfield       ┆ Children|Comedy                 │
│ 1022    ┆ Cinderella                   ┆ Animation|Children|Fantasy|Mus… │
└─────────┴──────────────────────────────┴─────────────────────────────────┘

In [ ]:
movies.describe()

shape: (9, 4)
┌────────────┬───────────────┬────────┬─────────┐
│ statistic  ┆ movieId       ┆ title  ┆ genres  │
│ ---        ┆ ---           ┆ ---    ┆ ---     │
│ str        ┆ f64           ┆ str    ┆ str     │
╞════════════╪═══════════════╪════════╪═════════╡
│ count      ┆ 80504.0       ┆ 80504  ┆ 80504   │
│ null_count ┆ 0.0           ┆ 0      ┆ 0       │
│ mean       ┆ 155501.531576 ┆ null   ┆ null    │
│ std        ┆ 81084.239109  ┆ null   ┆ null    │
│ min        ┆ 1.0           ┆        ┆ Action  │
│ 25%        ┆ 104285.0      ┆ null   ┆ null    │
│ 50%        ┆ 164739.0      ┆ null   ┆ null    │
│ 75%        ┆ 213756.0      ┆ null   ┆ null    │
│ max        ┆ 292757.0      ┆ 貞子3D ┆ Western │
└────────────┴───────────────┴────────┴─────────┘

In [ ]:
movies = movies.unique()

In [ ]:
movies.describe()

shape: (9, 4)
┌────────────┬───────────────┬────────┬─────────┐
│ statistic  ┆ movieId       ┆ title  ┆ genres  │
│ ---        ┆ ---           ┆ ---    ┆ ---     │
│ str        ┆ f64           ┆ str    ┆ str     │
╞════════════╪═══════════════╪════════╪═════════╡
│ count      ┆ 80504.0       ┆ 80504  ┆ 80504   │
│ null_count ┆ 0.0           ┆ 0      ┆ 0       │
│ mean       ┆ 155501.531576 ┆ null   ┆ null    │
│ std        ┆ 81084.239109  ┆ null   ┆ null    │
│ min        ┆ 1.0           ┆        ┆ Action  │
│ 25%        ┆ 104285.0      ┆ null   ┆ null    │
│ 50%        ┆ 164739.0      ┆ null   ┆ null    │
│ 75%        ┆ 213756.0      ┆ null   ┆ null    │
│ max        ┆ 292757.0      ┆ 貞子3D ┆ Western │
└────────────┴───────────────┴────────┴─────────┘

In [ ]:
movies = movies.with_columns(
    pl.col("genres").str.split("|")
).explode("genres")

# Agora cada linha tem apenas um género
print(movies.head(10))

shape: (10, 3)
┌─────────┬─────────────────────────────────┬─────────────┐
│ movieId ┆ title                           ┆ genres      │
│ ---     ┆ ---                             ┆ ---         │
│ i64     ┆ str                             ┆ str         │
╞═════════╪═════════════════════════════════╪═════════════╡
│ 249978  ┆ Andaz                           ┆ Drama       │
│ 144938  ┆ Money for Nothing: Inside the … ┆ Documentary │
│ 155555  ┆ Maïna                           ┆ Adventure   │
│ 155555  ┆ Maïna                           ┆ Drama       │
│ 246206  ┆ Polle fiction                   ┆ Comedy      │
│ 284567  ┆ Look At Me: XXXTENTACION        ┆ Documentary │
│ 173907  ┆ Le grand Méliès                 ┆ Documentary │
│ 173907  ┆ Le grand Méliès                 ┆ Drama       │
│ 129070  ┆ Cover Girl Models               ┆ Action      │
│ 129070  ┆ Cover Girl Models               ┆ Drama       │
└─────────┴─────────────────────────────────┴─────────────┘

<a class="anchor" id='lib'></a>
<font color = '#008000'>

## **2.3. Links** </font>

In [ ]:
links.head()

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [ ]:
links.describe()

             movieId        imdbId        tmdbId
count   87585.000000  8.758500e+04  8.746100e+04
mean   157651.365519  2.792840e+06  2.413823e+05
std     79013.402099  4.278866e+06  2.471467e+05
min         1.000000  1.000000e+00  2.000000e+00
25%    112657.000000  9.464200e+04  4.683600e+04
50%    165741.000000  4.929960e+05  1.392720e+05
75%    213203.000000  3.877296e+06  3.816930e+05
max    292757.000000  2.908110e+07  1.186337e+06

In [ ]:
links = links.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [ ]:
links.describe()

shape: (9, 4)
┌────────────┬───────────────┬─────────────┬───────────────┐
│ statistic  ┆ movieId       ┆ imdbId      ┆ tmdbId        │
│ ---        ┆ ---           ┆ ---         ┆ ---           │
│ str        ┆ f64           ┆ f64         ┆ f64           │
╞════════════╪═══════════════╪═════════════╪═══════════════╡
│ count      ┆ 87585.0       ┆ 87585.0     ┆ 87461.0       │
│ null_count ┆ 0.0           ┆ 0.0         ┆ 124.0         │
│ mean       ┆ 157651.365519 ┆ 2.7928e6    ┆ 241382.280422 │
│ std        ┆ 79013.402099  ┆ 4.2789e6    ┆ 247146.667043 │
│ min        ┆ 1.0           ┆ 1.0         ┆ 2.0           │
│ 25%        ┆ 112657.0      ┆ 94642.0     ┆ 46836.0       │
│ 50%        ┆ 165741.0      ┆ 492996.0    ┆ 139272.0      │
│ 75%        ┆ 213203.0      ┆ 3.877296e6  ┆ 381693.0      │
│ max        ┆ 292757.0      ┆ 2.9081098e7 ┆ 1.186337e6    │
└────────────┴───────────────┴─────────────┴───────────────┘

<a class="anchor" id='lib'></a>
<font color = '#008000'>

## **2.4. Tags** </font>

In [ ]:
tags.head()

shape: (5, 4)
┌────────┬─────────┬─────────────┬────────────┐
│ userId ┆ movieId ┆ tag         ┆ timestamp  │
│ ---    ┆ ---     ┆ ---         ┆ ---        │
│ i64    ┆ i64     ┆ str         ┆ i64        │
╞════════╪═════════╪═════════════╪════════════╡
│ 22     ┆ 26479   ┆ Kevin Kline ┆ 1583038886 │
│ 22     ┆ 79592   ┆ misogyny    ┆ 1581476297 │
│ 22     ┆ 247150  ┆ acrophobia  ┆ 1622483469 │
│ 34     ┆ 2174    ┆ music       ┆ 1249808064 │
│ 34     ┆ 2174    ┆ weird       ┆ 1249808102 │
└────────┴─────────┴─────────────┴────────────┘

In [ ]:
tags.describe()

shape: (9, 5)
┌────────────┬──────────────┬──────────────┬────────────────┬────────────┐
│ statistic  ┆ userId       ┆ movieId      ┆ tag            ┆ timestamp  │
│ ---        ┆ ---          ┆ ---          ┆ ---            ┆ ---        │
│ str        ┆ f64          ┆ f64          ┆ str            ┆ f64        │
╞════════════╪══════════════╪══════════════╪════════════════╪════════════╡
│ count      ┆ 2.000072e6   ┆ 2.000072e6   ┆ 2000072        ┆ 2.000072e6 │
│ null_count ┆ 0.0          ┆ 0.0          ┆ 0              ┆ 0.0        │
│ mean       ┆ 81928.586291 ┆ 71893.261729 ┆ null           ┆ 1.5289e9   │
│ std        ┆ 38106.498431 ┆ 74803.79499  ┆ null           ┆ 1.2908e8   │
│ min        ┆ 22.0         ┆ 1.0          ┆     The Asylum ┆ 1.1354e9   │
│ 25%        ┆ 68413.0      ┆ 4011.0       ┆ null           ┆ 1.4736e9   │
│ 50%        ┆ 78213.0      ┆ 52328.0      ┆ null           ┆ 1.5741e9   │
│ 75%        ┆ 103698.0     ┆ 122294.0     ┆ null           ┆ 1.6147e9   │
│ max        ┆ 162279.0     ┆ 292629.0     ┆ 카운트다운     ┆ 1.6972e9   │
└────────────┴──────────────┴──────────────┴────────────────┴────────────┘

In [ ]:
tags = tags.unique()

In [ ]:
tags.describe()

shape: (9, 5)
┌────────────┬──────────────┬──────────────┬────────────────┬────────────┐
│ statistic  ┆ userId       ┆ movieId      ┆ tag            ┆ timestamp  │
│ ---        ┆ ---          ┆ ---          ┆ ---            ┆ ---        │
│ str        ┆ f64          ┆ f64          ┆ str            ┆ f64        │
╞════════════╪══════════════╪══════════════╪════════════════╪════════════╡
│ count      ┆ 2.000072e6   ┆ 2.000072e6   ┆ 2000072        ┆ 2.000072e6 │
│ null_count ┆ 0.0          ┆ 0.0          ┆ 0              ┆ 0.0        │
│ mean       ┆ 81928.586291 ┆ 71893.261729 ┆ null           ┆ 1.5289e9   │
│ std        ┆ 38106.498431 ┆ 74803.79499  ┆ null           ┆ 1.2908e8   │
│ min        ┆ 22.0         ┆ 1.0          ┆     The Asylum ┆ 1.1354e9   │
│ 25%        ┆ 68413.0      ┆ 4011.0       ┆ null           ┆ 1.4736e9   │
│ 50%        ┆ 78213.0      ┆ 52328.0      ┆ null           ┆ 1.5741e9   │
│ 75%        ┆ 103698.0     ┆ 122294.0     ┆ null           ┆ 1.6147e9   │
│ max        ┆ 162279.0     ┆ 292629.0     ┆ 카운트다운     ┆ 1.6972e9   │
└────────────┴──────────────┴──────────────┴────────────────┴────────────┘

<a class="anchor" id='import'>
<font color = '#006400'>
    
# **3. Convert to Parquet** </font>
</a>

In [ ]:
# Define paths
output_dir = "~/Downloads"

# Make sure the directory exists
import os
os.makedirs(output_dir, exist_ok=True)

# Convert and save
ratings.write_parquet(os.path.join(output_dir, "ratings_32M.parquet"))
movies.write_parquet(os.path.join(output_dir, "movies_32M.parquet"))
links.write_parquet(os.path.join(output_dir, "links_32M.parquet"))
tags.write_parquet(os.path.join(output_dir, "tags_32M.parquet"))